config/routes.rb
Rails.application.routes.draw do
  get 'resource/title'

  get 'resource/link'

  get 'resource/description'

  resources :events

  devise_for :users
  root 'pages#home'

  get '/data', controller: 'pages', action: 'data'
  get '/naga', controller: 'pages', action: 'members'
  get '/resources', controller: 'pages', action: 'resources'

  get '/attend/:event_id', controller: 'events', action: 'attend'
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendances
  has_many :users, through: :attendances
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :attendances
  has_many :events, through: :attendances
end

app/controllers/accounts_controller.rb
class AccountsController < Devise::RegistrationController
  before_filter :configure_permitted_parameters

  def create
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :phone, :organization)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :surname
    devise_parameter_sanitizer.for(:account_update) << :grade

    devise_parameter_sanitizer.for(:account_update) << :student_id
    devise_parameter_sanitizer.for(:account_update) << :birthday
    devise_parameter_sanitizer.for(:account_update) << :gender
    devise_parameter_sanitizer.for(:account_update) << :address
    devise_parameter_sanitizer.for(:account_update) << :phone_number

    devise_parameter_sanitizer.for(:account_update) << :parent_name
    devise_parameter_sanitizer.for(:account_update) << :parent_email
    devise_parameter_sanitizer.for(:account_update) << :parent_phone_number

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @attendances = Attendance.all
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def attend
    u = current_user
    if current_user.name.blank? or current_user.surname.blank? or current_user.grade.blank? or u.student_id.blank? or u.gender.blank? or u.birthday.blank? or u.parent_email.blank? or u.parent_phone_number.blank? or u.address.blank? or u.parent_name.blank?
      flash[:alert] = "Finish filling out your settings before signing up for a conference!"
      redirect_to edit_user_registration_path
    else
      attendance = Attendance.create
      attendance.user_id = current_user.id
      attendance.event_id = params[:event_id]
      attendance.save!

      flash[:notice] = "You have successfully signed up for #{Event.find(params[:event_id]).name}. Submit checks to an officer or Ms. Balga."

      redirect_to '/events'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start, :end, :description, :img_url, :event_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to events_path
    end
  end

  def data
    @events = Event.all 
    @users = User.all
    @attendances = Attendance.all
  end

  def members
    @events = Event.all 
    @users = User.all
    @attendances = Attendance.all
  end

  def resources
    @resources = Resource.all 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resourceType(name)
    if name.downcase.include? "plan"
      return "Plans"
    elsif name.downcase.include? "exam"
      return "Exams"
    elsif name.downcase.include? "roleplay"
      return "Roleplays"
    else
      return "Miscellaneous"
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/index.html.erb
<div class="well">
  <strong>Directions</strong><br>

  Once you sign up for LACE, submit your check for $175 along with forms <a href="http://cl.ly/0h443I3M2A2Z/download/formd.pdf">D</a> and <a href="http://cl.ly/0M3n052r2J46/download/forme.pdf">E</a> to an officer (I suggest Mukil Loganathan) by Oct. 21, and you are good to go!
</div>

<% @events.each do |event| %>     
  <div class="well" style="padding: 0px">
    <div class="row">
      <div class="span2">
        <%= image_tag("event_#{event.id}.jpg", class: 'img-square img-thumbnail') %>
      </div>

      <div class="span5" style="margin-left:15px; margin-top:10px">
        <strong><p style="font-size:18px;"><%= event.name %></p></strong>
        <strong><p><%= event.start %> to <%= event.end %></p></strong>
        <p><%= event.description %></p>

        <p>
          <% if !event.users.include?(current_user) %>
            <%= link_to 'Register', "/attend/#{event.id}", confirm: '', class: 'btn btn-success' %>
            <a class="btn btn-primary" style="cursor: default;">Details</a>
          <% else %>
            <a class="btn btn-default" style="cursor: default;">You are signed up.</a>
          <% end %>

        </p>
      </div>
    </div>

  </div>
<% end %>

app/views/events/show.html.erb
<div class="page-header">
  <%= link_to events_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_event_path(@event), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show event</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @event.name %></dd>

  <dt>Start:</dt>
  <dd><%= @event.start %></dd>

  <dt>End:</dt>
  <dd><%= @event.end %></dd>

  <dt>Description:</dt>
  <dd><%= @event.description %></dd>

  <dt>Img url:</dt>
  <dd><%= @event.img_url %></dd>

</dl>

app/views/layouts/_header.html.erb
<div class="masthead">
  <ul class="nav nav-pills pull-right">
    <li class="active"><a href="#">Home</a></li>
    <li><a href="#">
      <i class="fa fa-sign-in fa-lg"></i>
    </a></li>
  </ul>
  <h3 class="muted">Cupertino DECA</h3>
</div>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cupertino DECA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-narrow">

  <div class="masthead">
    <ul class="nav nav-pills pull-right">
      
      <% if user_signed_in? %>
      <li><a href="/events">Events</a></li>
      <li><a href="/resources">Resources</a></li>
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li>
        <%= link_to "Data", '/data' if current_user.admin %>
      </li>
      <li>
        <%= link_to "Members", '/naga' if current_user.admin %>
      </li>
      <li><%= link_to "Exit", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
    <h3 class="muted" style="cursor: pointer;" onclick="window.location='/'">Cupertino DECA</h3>
  </div>

  <hr>

  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/pages/data.html.erb
<% if user_signed_in? and current_user.admin %>

  <h3>Members (<%= @users.count %>)</h3>
  <table class="table table-hover">
    <th>Name</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Grade</th>
    <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.surname %></td>
      <td><%= user.email%></td>
      <td><%= user.grade%></td>
    </tr>
    <% end %>
  </table>

  <h3>Registrations (<%= @attendances.count %>)</h3>
  <% for item in @attendances %>
    <table class="table table-hover">
      <tr>
        <td><%= "#{item.user.name} has signed up for #{item.event.name}."%></td>
      </tr>
    </table>
  <% end %>


<% else %>
  Admin users only.
<% end %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Learn to market</h1>
  <p class="lead">Join Cupertino DECA for the skills you need to succeed, today.</p>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-large btn-default' %>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-large btn-success' %>
</div>

<hr>

<div class="row-fluid marketing">
  <div class="span6">
    <h4>Study business</h4>
    <p>Study sessions provide the resources and opportunities to transform you into a business professional.</p>

    <h4>Win competitions</h4>
    <p>Past winners can help you place at the regional, state and even international levels.</p>
  </div>

  <div class="span6">
    <h4>Make friends</h4>
    <p>Networking events let you meet your future employees or investors.</p>

    <h4>Play hard</h4>
    <p>Achieve competitive excellence and have fun while doing so. Dances & socials allow for that!</p>
  </div>
</div>
<hr>

<div class="footer">
  <a id="naga" data-toggle="tooltip" title="Designed and developed by Tinovation (http://tinovation.org)">&copy; Cupertino DECA 2014-2015</a>

  <script type="text/javascript">
    $('#naga').tooltip();
  </script>

  <style type="text/css">
    #naga, #naga:hover {
      text-decoration: none;
      color: black;
    }
  </style>
</div>

app/views/pages/members.html.erb
<h3>Total attendees: <%= @attendances.all.count %></h3>

<% if !@attendances.blank? %>
  <% for attendance in @attendances %>

    <% user = attendance.user %>
    <div class="well">
      Name: <strong><%= user.name + " " + user.surname %></strong><br>
      Email: <strong><%= user.email %></strong><br>
      Grade: <strong><%= user.grade %></strong><br>

      <br>

      Student ID: <strong><%= user.student_id %></strong><br>
      Birthday: <strong><%= user.birthday %></strong><br>

      <br>

      Gender: <strong><%= user.gender %></strong><br>
      Address: <strong><%= user.address %></strong><br>
      Phone Number: <strong><%= user.phone_number %></strong><br>

      <br>

      Parent Name: <strong><%= user.parent_name %></strong><br>
      Parent Email: <strong><%= user.parent_email %></strong><br>
      Parent Number: <strong><%= user.parent_phone_number %></strong><br>

      <br>
      Last signed in: <strong><%= user.last_sign_in_at %></strong><br>
      Account created at: <strong><%= user.created_at %></strong><br>
    </div>

    <hr>
  <% end %>
<% else %>
  
<% end %>

app/views/pages/resources.html.erb
<select>
  <option>Plans</option>
  <option>Roleplays</option>
  <option>Exams</option>
  <option>Miscellaneous</option>
</select>

<hr style="margin-top: 10px">

<% for resource in @resources %>
  <div class="well <%= resourceType resource.title %>">
    <strong><p style="font-size:18px;"><a href="<%= resource.link %>"><%= resource.title %></p></a></strong>
    <p><%= resource.description %></p>
  </div>
<% end %>

<style type="text/css">

  a:hover {
    text-decoration: none;
  }

</style>

<script type="text/javascript">

  $(".well").hide();
  $(".Plans").show();

  $("select").change(function() {
    var className = $("select option:selected").text();

    $(".well").hide();
    $("." + className).show();
  });

</script>